# Generated by Django 5.1 on 2024-08-30 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='Course',
        ),
        migrations.AddField(
            model_name='course',
            name='Instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.instructor'),
        ),
    ]
