# Generated by Django 5.0 on 2024-09-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_enrollment_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='brochure_file',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
